version: '3'

services:
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        image: "herbalheal-backend"
        ports:
            - "8000:8000"
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        image: "herbalheal-frontend"
        ports:
            - "3000:80"
